### ISSUE TITLE
Notification Todo

### ISSUE THREAD

**Issue by daehwan2da** [Team-Smeme/smeem-aos#1]
### FCM
- [x] android fcm sdk 세팅
- [x] fcm 연동 확인
  - google.json 공유해줘야함
    - [ ] 태희
    - [ ] 수민

### implementation
- [channel](https://developer.android.com/develop/ui/views/notifications/channels?hl=en)
  - [ ] 채널은 어떻게 구성해야할지?
    - [ ] 채널이랑 그룹의 구분은 어떻게 되고, 어떻게 활용할지?
- [ ] aos API 버전 분기
- [ ] [권한 허용 여부에 따른 분기](https://developer.android.com/reference/android/app/NotificationManager#areNotificationsEnabled())

### 알림 ui
[docs](https://developer.android.com/develop/ui/views/notifications?hl=en)
  - [custom](https://developer.android.com/develop/ui/views/notifications/custom-notification?hl=en)

[material](https://m2.material.io/design/platform-guidance/android-notifications.html#anatomy-of-a-notification)
- [ ] Status Bar
- [ ] Heads-up
- [ ] Lock Screen
- [ ] App icon Badge
- [ ] Detail
  - [ ] small icon
  - [ ] when
  - [ ] large icon
  - [ ] actions

### 알림 권한 확인 
[docs](https://developer.android.com/develop/ui/views/notifications/notification-permission?hl=en)
[fcm](https://firebase.google.com/docs/cloud-messaging/android/client?hl=en#request-permission13)
- [ ] over API 33
- [ ] under API 32

**Comment by daehwan2da** [comment]
해당 관련 작업은 base/notification 을 base 잡고 진행합니다.
( merge : feature -> base -> (테스트 완료 후) -> develop)
