### ISSUE TITLE
Splash Todo

### ISSUE THREAD

**Issue by daehwan2da** [Team-Smeme/smeem-aos#10]
### Login
- [x] UI 구현
  - [x] splash-1
  - [x] splash-2
- [x] 이미 계정이 있는 경우
  - [x] 카카오 로그인 구현
  - [x] 카카오 로그인 isRegistered
    - [x] true : 바로 home 으로 이동
    - [x] false : #11 로 이동
      - [x] isPlanRegistered (가칭, 학습목표설정 여부)
        - [x] true : 닉네임 세팅으로 이동
        - [x] false : 학습목표 설정 진행
- [x] 시작하기
  - [x] #11 로 이동

## Splash-1
<img width="768" alt="스크린샷 2023-05-03 오후 9 20 42" src="https://user-images.githubusercontent.com/88091704/235913862-75c4b5eb-f1f1-43c6-ad58-6ba4d7b1b4c1.png">

## Splash-2
<img width="802" alt="스크린샷 2023-05-03 오후 9 20 54" src="https://user-images.githubusercontent.com/88091704/235913912-3de4d2de-e994-486d-b767-bb6dc35416cb.png">

- [x] UI 구현
