### ISSUE TITLE
onBoarding Todo

### ISSUE THREAD

**Issue by daehwan2da** [Team-Smeme/smeem-aos#11]
## onBoarding
- [ ] UI 구성
  - [x] 학습 목표 설정
  - [x] 학습 권장 방법
  - [ ] 학습 시간 설정
    - [ ] time picker custom 이후 구현
  - [ ] 알림 권한 허용 설정
    - access token 유무에 따른 분기
      - [x] 유 : 학습목표 PATCH api call, 회원가입 바텀 시트 띄우지 않음
      - [x] 무 : 회원 가입 바텀시트 띄움
  - [x] 닉네임 설정
  - [x] 이용약관 설정
- [x] oauth 회원가입 바텀 시트
  - [x] kakao 인증 후 access token 발급
  - [x] 회원목표 PATCH api call
- [x] API call
  - [x] 학습 목표 PATCH
    - request
      - 학습 목표
      - 학습 권장 방법
      - 학습 시간 
  - [ ] 유저 정보 PATCH
    - request
      - 닉네임, 이용약관 동의 내용 
- [ ] 뷰 이동
  - [x] #4

<img width="1074" alt="스크린샷 2023-05-03 오후 9 31 40" src="https://user-images.githubusercontent.com/88091704/235916750-837030f7-95fd-44e2-884d-38f7c75ad09e.png">
<img width="1017" alt="스크린샷 2023-05-03 오후 9 31 49" src="https://user-images.githubusercontent.com/88091704/235916776-ff068d1e-8823-48ca-b031-fee8e36176af.png">
<img width="1049" alt="스크린샷 2023-05-03 오후 9 31 57" src="https://user-images.githubusercontent.com/88091704/235916803-28f54739-53ef-487e-ae58-6d385c1f30b9.png">
<img width="1048" alt="스크린샷 2023-05-03 오후 9 32 07" src="https://user-images.githubusercontent.com/88091704/235916844-4396d7d8-4191-4f40-b24d-91bfa1b45929.png">
<img width="1071" alt="스크린샷 2023-05-03 오후 9 32 46" src="https://user-images.githubusercontent.com/88091704/235916995-9e09206e-e757-42f6-a0bd-9f0029093483.png">
<img width="1118" alt="스크린샷 2023-05-03 오후 9 32 57" src="https://user-images.githubusercontent.com/88091704/235917022-ab7c3164-95e9-4b31-b949-426cb7a056ac.png">
<img width="1165" alt="스크린샷 2023-05-03 오후 9 33 06" src="https://user-images.githubusercontent.com/88091704/235917052-7d3b548f-f56d-46a1-9c5f-a807e1b3f880.png">

**Comment by daehwan2da** [comment]
### 이탈 시
- onBoarding 최초 화면으로 
  - 기존 데이터 무시
