### ISSUE TITLE
오래된 버전일 때 업데이트 알림 띄우기

### ISSUE THREAD

**Issue by wateralsie** [Team-Smeme/smeem-aos#163]
## *Todo*
- [x] firebase의 remote config를 사용한 방법
or
- [ ] in-app update
- [ ] 릴리즈 후 링크 추가

### remote config
https://all-dev-kang.tistory.com/entry/안드로이드-앱-업데이트를-관리하는-방법-1
https://firebase.google.com/docs/remote-config
https://firebase.google.com/docs/remote-config/get-started?platform=android
### in-app
https://developer.android.com/guide/playcore/in-app-updates/kotlin-java
https://medium.com/android-news/implement-in-app-update-in-android-68892bd11e35
