### ISSUE TITLE
캘린더 핸들링 개선 

### ISSUE THREAD

**Issue by daehwan2da** [Team-Smeme/smeem-aos#64]
### TODO
캘린더 시트 핸들링 과정에서 부자연스러운 UI 및 디자인에 맞게 구현되도록 개선

### Check List
- [ ] Month <-> Week 펼치고 접는 과정중 중간에 부자연스럽게 생기고 사라지는 Month, Week view 개선
- [ ] BottomSheet EXPANDED 상태에서 bottom sheet 의 View 가 정상적으로 보이지 않음 개선
  - 일기가 없는 경우 일기없음, 있는 경우 일기 노출
- [ ] 핸들 슬라이드시 순간적으로 캘린더 전체가 접히는 이슈 개선

## Before

https://github.com/Team-Smeme/smeem-aos/assets/88091704/002f6490-00a0-408f-9cdf-333b5ab0337c
